// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvoSb_dGMwlvHWhmKtRwvX3mlajU5f6pQ',
    appId: '1:278726956859:web:574c145e3e06b4d89e891e',
    messagingSenderId: '278726956859',
    projectId: 'nomad-final-movieapp',
    authDomain: 'nomad-final-movieapp.firebaseapp.com',
    storageBucket: 'nomad-final-movieapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFh0BKYCqAfWcZvymNhzkFFh-IqkdOXo',
    appId: '1:278726956859:android:5518de74d3e7be289e891e',
    messagingSenderId: '278726956859',
    projectId: 'nomad-final-movieapp',
    storageBucket: 'nomad-final-movieapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9vRPewF52nhu_WGK-4H-0HXDKvBEQ0jo',
    appId: '1:278726956859:ios:4b3506610684a5f69e891e',
    messagingSenderId: '278726956859',
    projectId: 'nomad-final-movieapp',
    storageBucket: 'nomad-final-movieapp.firebasestorage.app',
    iosBundleId: 'com.example.nomadMovieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9vRPewF52nhu_WGK-4H-0HXDKvBEQ0jo',
    appId: '1:278726956859:ios:4b3506610684a5f69e891e',
    messagingSenderId: '278726956859',
    projectId: 'nomad-final-movieapp',
    storageBucket: 'nomad-final-movieapp.firebasestorage.app',
    iosBundleId: 'com.example.nomadMovieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvoSb_dGMwlvHWhmKtRwvX3mlajU5f6pQ',
    appId: '1:278726956859:web:392ab8f6bae9dd329e891e',
    messagingSenderId: '278726956859',
    projectId: 'nomad-final-movieapp',
    authDomain: 'nomad-final-movieapp.firebaseapp.com',
    storageBucket: 'nomad-final-movieapp.firebasestorage.app',
  );

}